---
title: "IPD Background"
author: "Lok Yiu Xuan [23171563]"
date: "2025-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(splines)
library(rms)
library(lme4)
library(ggplot2)
```

```{r}
myfunc <- "10 + 5 * (1 + exp((.15 * (X1 - 60))))^(-1)"
plot_data <- tibble(X1 = seq(20, 100, length.out = 200)) %>%
  mutate(Y = eval(parse(text = myfunc)))
ggplot(plot_data, aes(x = X1, y = Y)) +
  geom_line(color = "blue", linewidth = 1.5) +
  labs(title = "Plot of myfunc",
       x = "X1",
       y = "Y") +
  theme_minimal()
```


# Read Data
```{r}
ipd_data <- read_csv("../data/generated_ipd.csv") %>%
  mutate(Study = as.factor(Study))

nrow(ipd_data)
```
```{r}
noise_sd <- 2
set.seed(10)
ipd_data <- ipd_data %>%
  mutate(Y = Y + rnorm(n(), mean = 0, sd = noise_sd))
```

```{r}
dd <- datadist(ipd_data)
options(datadist = "dd")

make_rcs <- function(data, variable = "X", knots = NULL, n = NULL, dp = 1) {
  quan <- list(
    '3' = c(0.10, 0.50, 0.90),
    '4' = c(0.05, 0.35, 0.65, 0.95),
    '5' = c(0.05, 0.275, 0.50, 0.725, 0.95),
    '6' = c(0.05, 0.23, 0.41, 0.59, 0.77, 0.95),
    '7' = c(0.025, 0.1833, 0.3417, 0.50, 0.6583, 0.8167, 0.975)
  )
  
  if (!is.null(n)) {
    knot_str <- paste(n, collapse = ", ")
    return(sprintf("rcs(%s, %s)", variable, knot_str))
  }
  
  if (!is.null(knots)) { 
    preset_str <- as.character(knots) 
    if (preset_str %in% names(quan)) { 
      knot_values <- quantile(data, probs = quan[[preset_str]], na.rm = TRUE) 
      knot_str <- paste(round(knot_values, dp), collapse = ", ") 
      return(sprintf("rcs(%s, c(%s))", variable, knot_str)) 
    } 
  }
  
  return(sprintf("rcs(%s)", variable))
}
```

```{r}
tapply(ipd_data$Age, ipd_data$Study, FUN = function(x) make_rcs(x, variable = "Age", knots = 3))
plot(ipd_data$Y ~ ipd_data$Age, col=ipd_data$Study)
```
# Stage 1
## Fit study-specific spline models
```{r}
studies <- unique(ipd_data$Study)
study_models <- setNames(lapply(studies, function(s) {
  study_data <- subset(ipd_data, Study == s)
  pred_str <- make_rcs(study_data$Age, "Age", knots = 3)
  formula_obj <- as.formula(paste0("Y ~ ", pred_str))
  model <- ols(formula_obj, data = study_data)
  
  list(
    study = s,
    formula = formula_obj,
    data = study_data,
    model = model,
    fitted = fitted(model),
    residuals = residuals(model)
  )
}), studies)
```

## Predictions per study
```{r}
pred_ori_data <- do.call(rbind, lapply(study_models, function(sm) {
  data.frame(
    study = sm$study,
    Age   = sm$data$Age,
    Y     = predict(sm$model, newdata = sm$data)
  )
}))
head(pred_ori_data)
```
## Plots
```{r}
ggplot() +
  geom_point(data = ipd_data, aes(x = Age, y = Y, color = Study), alpha = 0.3) +
  geom_line(data = pred_ori_data, aes(x = Age, y = Y, color = study), linewidth = 1) +
  facet_wrap(~study, scales = "free") +
  labs(title = "Stage 1: Study-specific Splines", x = "Age", y = "Y") +
  theme_minimal()

# residuals
residuals_list <- lapply(study_models, function(sm) {
  data.frame(
    study = sm$study,
    fitted = sm$fitted,
    residuals = sm$residuals
  )
})
residuals_df <- do.call(rbind, residuals_list)


ggplot(residuals_df, aes(x = fitted, y = residuals)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~study, scales = "free_x") +
  labs(title = "Stage 1 Residuals vs Fitted", x = "Fitted", y = "Residuals") +
  theme_minimal()
```
## Extract and summarize results
```{r}
stage1_summary_list <- lapply(study_models, function(sm) {
  rmse <- sqrt(mean(sm$residuals^2))
  data.frame(
    study = sm$study,
    formula = paste(sm$formula, collapse = " "),
    r_squared = sm$model$stats["R2"],
    rmse = rmse,
    n = nrow(sm$data)
  )
})

stage1_summary <- do.call(rbind, stage1_summary_list)
stage1_summary
```
```{r}
# map(study_models, ~ (.$model))
```

# Stage 2
## Method 1: Combine all studies as 1 pooled dataset
```{r}
combined_data <- pred_ori_data
plot(combined_data$Y~combined_data$Age, col=combined_data$study)
# plot(pred_ori_data$Y~pred_ori_data$Age)
```
```{r}
combined_data$study <- 1
combined_pred_str <- make_rcs(combined_data$Age, "Age", knots = 3)
pooled_formula <- as.formula(paste0("Y ~ ", combined_pred_str))
pooled_model <- ols(pooled_formula, data = combined_data)

common_grid1 <- tibble(Age = seq(min(combined_data$Age), max(combined_data$Age), length.out = 100))
pred1 <- predict(pooled_model, newdata = common_grid1, se.fit=T)
common_grid1$Y <- pred1$linear.predictors
common_grid1$lower <- pred1$linear.predictors - 1.96 * pred1$se.fit
common_grid1$upper <- pred1$linear.predictors + 1.96 * pred1$se.fit

# ggplot() +
#   geom_line(data=pred_ori_data, aes(x = Age, y = Y, color = study), alpha = 0.5) +
#   geom_line(data = common_grid1, aes(x = Age, y = Y), color = "blue", linewidth = 1) +
#   geom_ribbon(data = common_grid1, aes(x = Age, ymin = lower, ymax = upper), fill = "blue", alpha = 0.2) +
#   labs(title = "Combined Pooled Spline with 95% CI", x = "Age", y = "Predicted Y") +
#   theme_minimal()
```
## Method 2: Meta-analysis using per-study predicted splines
```{r}
meta_data <- pred_ori_data

meta_formula <- as.formula(paste0("Y ~ ", combined_pred_str, "+ (1 | study)"))
meta_model <- lmer(meta_formula, data = meta_data)

meta_data$Y_pred <- predict(meta_model, newdata = meta_data, re.form = NA)

# ggplot(meta_data) +
#   geom_line(aes(x = Age, y = Y, color = study), alpha = 0.5) +
#   geom_line(aes(x = Age, y = Y_pred), color = "red", linewidth = 1.0) +
#   labs(
#     title = "Stage 2 (Method 2): Meta-Analysed Splines",
#     x = "Age",
#     y = "Predicted Y"
#   ) +
#   theme_minimal()
```
## combine
```{r}
ggplot() +
  geom_point(data = ipd_data, aes(x = Age, y = Y, color = Study), alpha = 0.3) +

  geom_line(data = pred_ori_data, aes(x = Age, y = Y, color = study), 
            alpha = 0.5) +

  geom_line(data = plot_data, aes(x = X1, y = Y), color = "black", linewidth = 1) +
  geom_line(data = common_grid1, aes(x = Age, y = Y), 
            color = "blue", linewidth = 1) +
  geom_ribbon(data = common_grid1, aes(x = Age, ymin = lower, ymax = upper), 
              fill = "blue", alpha = 0.2) +
  
  geom_line(data = meta_data, aes(x = Age, y = Y_pred), 
            color = "red", linewidth = 1.0) +
  
  labs(
    title = "Stage 2: Combined Pooled and Meta-Analysed Splines",
    x = "Age",
    y = "Predicted Y"
  ) +
  theme_minimal()

# ggplot(plot_data, aes(x = X1, y = Y)) +
#   geom_line(color = "blue", linewidth = 1.5) +
#   labs(title = "Plot of myfunc",
#        x = "X1",
#        y = "Y") +
#   theme_minimal()
```
--weights to mix model?

## Method 2: random effect
```{r}
meta_data_re <- pred_ori_data

meta_formula <- as.formula(paste0("Y ~ ", combined_pred_str, " + (1 | study)"))
meta_model <- lmer(meta_formula, data = meta_data_re)

meta_data_re$Y_pred <- predict(meta_model, newdata = meta_data_re)
ggplot(meta_data_re) +
  geom_line(aes(x = Age, y = Y, color = study), alpha = 0.5) +
  geom_line(aes(x = Age, y = Y_pred, color = study), linewidth = 1.0) +
  labs(
    title = "Stage 2: Meta-Analysed Splines Including Study Random Effects",
    x = "Age",
    y = "Predicted Y"
  ) +
  theme_minimal()
```
