---
title: "Simulation Analysis Version 2"
author: "Lok Yiu Xuan [23171563]"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rms)
source("../scripts/helpers.R")
```
# Read Settings
```{r}
file_dir_some <- "../data/simulate3/simulated_some/"
simul_settings_some <- read_csv(paste0(file_dir_some, "simul_settings.csv"), show_col_types = FALSE)
# Exclude same knots file
study_cols <- grep("^Study", names(simul_settings_some), value = TRUE)
# Apply filter
# simul_settings_some <- simul_settings_some[!apply(simul_settings_some, 1, is_same_knots), ]
```

# Compare
## Method
```{r}
ggplot(simul_settings_some, aes(x=Rank_pooled, y=Rank_meta)) +geom_point()
```
## CI Coverage
```{r, fig.width = 14, fig.height = 8}
plot_CI_coverage(simul_settings_some)
plot_CI_coverage(simul_settings_some, arrange_by = "knots")
```

```{r}
exclude_cols <- c("Stage2", 
                  grep("^MSE", names(simul_settings_some), value = TRUE), 
                  grep("^Study", names(simul_settings_some), value = TRUE), 
                  grep("^Rank_", names(simul_settings_some), value = TRUE))

top_n <- 1
worst_n <- 0
rank_all_some <- make_rank_all(simul_settings_some, top_n, worst_n)

rank_cols <- grep("^Rank_", names(simul_settings_some), value = TRUE)
# Factor with desired order
methods <- unique(rank_all_some$rank_method)
lvls <- c(paste0("best", 1:top_n), paste0("worst", worst_n:1))
rank_all_some %>% dplyr::select(-all_of(exclude_cols))
```
# Read Simulation Data
```{r}
sim_data_some <- list()
for (i in 1:nrow(rank_all_some)) {
  df_row <- rank_all_some[i,]
  filename <- paste0(file_dir_some, df_row$Name, ".csv")
  sim_df <- read_csv(filename, show_col_types = FALSE)
  stage2_knots_str <- df_row$Stage2

  sim_data_some[[i]] <- sim_df %>%
    mutate(
      stage2_quantiles_str = stage2_knots_str,
      stage2_knots = length(knots_to_numeric(stage2_knots_str)),
      study_knots = word(df_row$Name, 1, sep = "_"),
      rank_method = df_row$rank_method,
      rank_id = df_row$rank_id
    )
}
names(sim_data_some) <- rank_all_some$Name
```
```{r}
ori_data_some <- sim_data_some[[1]] %>%
  filter(method == "pooled") %>%
  select(Study, Y, Age) %>%
  mutate(Study = as.factor(Study))

ggplot(ori_data_some) +
  geom_point(aes(x = Age, y = Y, color = as.factor(Study)), shape=1) +
  labs(title = "Simulated True Data (Some Overlap)", x = "Age", y = "Y",
       color = "Study") +
  theme(legend.position = "bottom",
        legend.text   = element_text(size = 14)) +
  guides(
    color = guide_legend(ncol = 6, override.aes = list(shape = 16))
  )
  # facet_wrap(~Study, scales = "fixed")
```

# Calculate Metrics Reduce df
```{r}
all_metrics_some <- lapply(sim_data_some, function(df) {
  lapply(methods, function(m) {
    df_filtered <- df %>% filter(method == m)
    calculate_metrics(df_filtered, level = 0.95) %>%
      mutate(method = m)
  }) %>% bind_rows()
})
```
# Summary of all
```{r}
metrics <- c("mse", "variance", "bias")
# Apply summary to all_metrics_some
summary_all_some <- set_summary(all_metrics_some, metrics = metrics)
summary_all_some
```
# Bias, Variance, MSE plot
## n=1800
```{r}
df_all_some <- bind_rows(all_metrics_some)
df_plot_some <- df_all_some %>%
  filter(
    method == rank_method,
    method != "meta_re"
  ) %>%
  mutate(
    line_id = paste0(method, "_", study_knots),
    rank_id = factor(rank_id, levels = lvls)  # enforce order
  ) %>%
  pivot_longer(
    cols = all_of(metrics),
    names_to = "metric_name",
    values_to = "metric_value"
  )

ff_line_id <- unique(df_plot_some$line_id)
ff_line_id <- ff_line_id[c(3, 1, 4, 2)]
df_plot_some <- df_plot_some %>% mutate(line_id = factor(line_id, levels = ff_line_id))
```
### line plot
```{r}
# df_plot_some2 <- df_plot_some %>% filter(rank_id == "best1")

plots_some <- lapply(metrics, function(m) base_plot(df_plot_some, m, ncol=2,
                                                    legend_ncol=2, legend_size=15))
plots_some
```
#### Combine
```{r, fig.width=18, fig.height=5}
ppp_some <- 
  base_plot(df_plot_some, metrics[1], ncol=2, legend_ncol=2, legend_size=15)+
  base_plot(df_plot_some, metrics[2], ncol=2, legend_ncol=2, legend_size=15)+
  base_plot(df_plot_some, metrics[3], ncol=2, legend_ncol=2, legend_size=15)
ppp_some
```

### CI True Value
```{r}
plot_CI_some <- base_plot_CI(df_plot_some, ncol = 2,
                             legend_ncol=2, legend_size=15)
plot_CI_some
```

