---
title: "Simulation Extrapolation Analysis Version 2"
author: "Lok Yiu Xuan [23171563]"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rms)
library(patchwork)
source("../scripts/helpers.R")
```
# Read Settings
```{r}
file_dir_some_e <- "../data/extrapolate3/simulated_some/"
simul_settings_some_e <- read_csv(paste0(file_dir_some_e, "simul_settings.csv"), show_col_types = FALSE)
# Exclude same knots file
study_cols <- grep("^Study", names(simul_settings_some_e), value = TRUE)
# Apply filter
# simul_settings_some_e <- simul_settings_some_e[
#   !apply(simul_settings_some_e, 1, is_same_knots), 
# ]
```

# Compare
## Rank Method
```{r}
rank_some_e <- plot_rank_method(simul_settings_some_e)
rank_some_e
```

## CI Coverage
```{r, fig.width = 13, fig.height = 6}
p_CI_cover_some_e <- plot_CI_coverage(simul_settings_some_e, base_knot = 5)
p_CI_cover_some_e
```

```{r}
exclude_cols <- c("Stage2", 
                  grep("^MSE", names(simul_settings_some_e), value = TRUE), 
                  grep("^Study", names(simul_settings_some_e), value = TRUE), 
                  grep("^Rank_", names(simul_settings_some_e), value = TRUE))

top_n <- 1
worst_n <- 1
rank_all_some_e <- make_rank_all(simul_settings_some_e, top_n, worst_n)

rank_cols <- grep("^Rank_", names(simul_settings_some_e), value = TRUE)
# Factor with desired order
methods <- unique(rank_all_some_e$rank_method)
lvls <- levels(rank_all_many$rank_id)

rank_all_some_e %>% dplyr::select(-all_of(exclude_cols))
```
# Read Simulation Data
```{r}
sim_data_some_e <- load_sim_data(rank_all_some_e, file_dir_some_e)
```


```{r}
ggplot(sim_data_some_e[[1]]) +
  geom_point(aes(x = Age, y = Y, color = as.factor(Study)), shape=1) +
  labs(title = "Simulated True Data (Some Overlap)", 
       x = "Age", y = "Y", color = "Study")
  # facet_wrap(~Study, scales = "fixed")
```

# Calculate Metrics Reduce df
```{r}
all_metrics_some_e <- lapply(sim_data_some_e, function(df) {
  lapply(methods, function(m) {
    df_filtered <- df %>% filter(method == m)
    calculate_metrics(df_filtered, level = 0.95) %>%
      mutate(method = m)
  }) %>% bind_rows()
})
```
# Summary of all
```{r}
metrics <- c("mse", "variance", "bias")
# Apply summary to all_metrics_some_e
summary_all_some_e <- set_summary(all_metrics_some_e, metrics = metrics)
summary_all_some_e %>% arrange(method, rank_id)
```
# Bias, Variance, MSE plot
```{r}
df_all_some_e <- bind_rows(all_metrics_some_e)
df_plot_some_e <- df_all_some_e %>%
  filter(
    method == rank_method,
    method != "meta_re"
  ) %>%
  mutate(
    line_id = paste0(method, "_", study_knots),
    rank_id = factor(rank_id, levels = lvls)  # enforce order
  ) %>%
  pivot_longer(
    cols = all_of(metrics),
    names_to = "metric_name",
    values_to = "metric_value"
  )
df_plot_some_e$line_id <- factor(df_plot_some_e$line_id, levels = unique(df_plot_some_e$line_id))
```
### line plot
```{r, fig.width=12, fig.height=5}
plots_some_e <- lapply(metrics, function(m) base_plot(
  df_plot_some_e, m, ncol=3, legend_ncol=4))
plots_some_e[[1]]
plots_some_e[[2]]
plots_some_e[[3]]
```

### CI True Value
```{r, fig.width=12, fig.height=5}
plot_CI_some_e <- base_plot_CI(df_plot_some_e, ncol = 3, legend_ncol=4)
plot_CI_some_e
```

