---
title: "Simulation Extrapolation Analysis Version 2"
author: "Lok Yiu Xuan [23171563]"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rms)
library(patchwork)
source("../scripts/helpers.R")
```
# Read Settings
```{r}
file_dir_no_e <- "../data/extrapolate3/simulated_no/"
simul_settings_no_e <- read_csv(paste0(file_dir_no_e, "simul_settings.csv"), show_col_types = FALSE)
# Exclude same knots file
study_cols <- grep("^Study", names(simul_settings_no_e), value = TRUE)
# Apply filter
# simul_settings_no_e <- simul_settings_no_e[!apply(simul_settings_no_e, 1, is_same_knots), ]
```

# Compare
## Method
```{r}
ggplot(simul_settings_no_e, aes(x=Rank_pooled, y=Rank_meta)) +geom_point()
```
## CI Coverage
```{r, fig.width = 14, fig.height = 8}
plot_CI_coverage(simul_settings_no_e)
plot_CI_coverage(simul_settings_no_e, arrange_by = "knots")
```

```{r}
exclude_cols <- c("Stage2", 
                  grep("^MSE", names(simul_settings_no_e), value = TRUE), 
                  grep("^Study", names(simul_settings_no_e), value = TRUE), 
                  grep("^Rank_", names(simul_settings_no_e), value = TRUE))

top_n <- 1
worst_n <- 1
rank_all_no_e <- make_rank_all(simul_settings_no_e, top_n, worst_n)

rank_cols <- grep("^Rank_", names(simul_settings_no_e), value = TRUE)
# Factor with desired order
methods <- unique(rank_all_no_e$rank_method)
lvls <- c(paste0("best", 1:top_n), paste0("worst", worst_n:1))
rank_all_no_e %>% dplyr::select(-all_of(exclude_cols))
```
# Read Simulation Data
```{r}
sim_data_no_e <- list()
for (i in 1:nrow(rank_all_no_e)) {
  df_row <- rank_all_no_e[i,]
  filename <- paste0(file_dir_no_e, df_row$Name, ".csv")
  sim_df <- read_csv(filename, show_col_types = FALSE)
  stage2_knots_str <- df_row$Stage2

  sim_data_no_e[[i]] <- sim_df %>%
    mutate(
      stage2_quantiles_str = stage2_knots_str,
      stage2_knots = length(knots_to_numeric(stage2_knots_str)),
      study_knots = word(df_row$Name, 1, sep = "_"),
      rank_method = df_row$rank_method,
      rank_id = df_row$rank_id
    )
}
names(sim_data_no_e) <- rank_all_no_e$Name
```
```{r}
ggplot(sim_data_no_e[[1]]) +
  geom_point(aes(x = Age, y = Y, color = as.factor(Study)), shape=1) +
  labs(title = "Simulated True Data (No Overlap)", x = "Age", y = "Y",
       color = "Study")
  # facet_wrap(~Study, scales = "fixed")
```
# Calculate Metrics Reduce df
```{r}
all_metrics_no_e <- lapply(sim_data_no_e, function(df) {
  lapply(methods, function(m) {
    df_filtered <- df %>% filter(method == m)
    calculate_metrics(df_filtered, level = 0.95) %>%
      mutate(method = m)
  }) %>% bind_rows()
})
```
# Summary of all
```{r}
metrics <- c("mse", "variance", "bias")
# Apply summary to all_metrics_no_e
summary_all_no_e <- set_summary(all_metrics_no_e, metrics = metrics)
summary_all_no_e %>% arrange(method, rank_id)
```
# Bias, Variance, MSE plot
```{r}
df_all_no_e <- bind_rows(all_metrics_no_e)
df_plot_no_e <- df_all_no_e %>%
  filter(
    method == rank_method
  ) %>%
  mutate(
    line_id = paste0(method, "_", study_knots),
    rank_id = factor(rank_id, levels = lvls)  # enforce order
  ) %>%
  pivot_longer(
    cols = all_of(metrics),
    names_to = "metric_name",
    values_to = "metric_value"
  )
```

### line plot
```{r, fig.width=12, fig.height=6}
plots_no_e <- lapply(metrics, function(m) base_plot(df_plot_no_e, m, 
                                                  ncol=3, legend_ncol=1))
wrap_plots(
  list(plots_no_e[[1]], plots_no_e[[2]], plots_no_e[[3]]),
  ncol=3,
)
```
### CI True Value
```{r, fig.width=12}
plot_CI_no_e <- base_plot_CI(df_plot_no_e, ncol = 2, legend_ncol = 4,
                           jitter_height = 0, show_jitter = T)
plot_CI_no_e
```