---
title: "Simulation Analysis Version 2"
author: "Lok Yiu Xuan [23171563]"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(patchwork)
library(metafor)
```
# Read Settings
```{r}
file_dir <- "../data/simulated_no/"
simul_settings <- read_csv(paste0(file_dir, "simul_settings.csv"), show_col_types = FALSE)
```
```{r}
knots_to_numeric <- function(knots_str) {
  # Handle NA or empty string
  if (is.na(knots_str) || knots_str == "") {
    return(c(0))
  }
  # Split by comma, trim whitespace, and convert to numeric
  as.numeric(trimws(unlist(strsplit(knots_str, ","))))
}

# Exclude same knots file
study_cols <- grep("^Study", names(simul_settings), value = TRUE)

# Function to check if Stage2 == all Study columns
is_same_knots <- function(row) {
  all(sapply(study_cols, function(c){
    length(knots_to_numeric(row[[c]])) == length(knots_to_numeric(row[["Stage2"]]))
  }))
}
# Apply filter
simul_settings <- simul_settings[!apply(simul_settings, 1, is_same_knots), ]
```

```{r}
rank_cols <- grep("^Rank_", names(simul_settings), value = TRUE)
methods <- sub("^Rank_", "", rank_cols)

exclude_cols <- c("Stage2", 
                  grep("^MSE", names(simul_settings), value = TRUE),
                  grep("^Study", names(simul_settings), value = TRUE))

good <- 2
worse <- 1
top <- good+worse

top_all <- lapply(rank_cols, function(col) {
  best <- simul_settings %>%
    arrange(.data[[col]]) %>%
    slice(1:good) %>%
    mutate(rank_method = sub("^Rank_", "", col),
           type = "good")
  
  worst <- simul_settings %>%
    arrange(.data[[col]]) %>%
    slice_tail(n = worse) %>%
    mutate(rank_method = sub("^Rank_", "", col),
           type = "worst")
  
  bind_rows(best, worst) %>%
    mutate(rank_id = row_number())
}) %>%
  bind_rows()

top_all %>% select(-all_of(exclude_cols))
```
# Read Simulation Data
```{r}
sim_data_no <- list()
for (i in 1:nrow(top_all)) {
  df_row <- top_all[i,]
  filename <- paste0(file_dir, df_row$Name, ".csv")
  sim_df <- read_csv(filename, show_col_types = FALSE)
  stage2_knots_str <- df_row$Stage2

  sim_data_no[[i]] <- sim_df %>%
    mutate(
      stage2_quantiles_str = stage2_knots_str,
      stage2_knots = length(knots_to_numeric(stage2_knots_str)),
      study_knots = word(df_row$Name, 1, sep = "_"),
      rank_method = df_row$rank_method,
      rank_id = df_row$rank_id
    )
}
names(sim_data_no) <- top_all$Name
```
```{r}
plot(Y~Age, col=Study, data=sim_data_no[[1]])
```
# Calculate Metrics Reduce df
```{r}
calculate_metrics <- function(df, level = 0.95) {
  # Identify simulation columns
  sim_cols <- grep("^sim_", names(df), value = TRUE)
  Y_true <- df$Y
  
  alpha <- 1 - level
  z_val <- qnorm(1 - alpha / 2)
  
  # Extract simulation matrix for easier computation
  sim_matrix <- as.matrix(df[, sim_cols])
  row_means <- rowMeans(sim_matrix)
  row_vars <- apply(sim_matrix, 1, var)
  row_mses <- rowMeans((sim_matrix - Y_true)^2)
  
  tibble(
    Age = df$Age,
    Y_true = Y_true,
    bias = row_means - Y_true,
    variance = row_vars,
    mse = row_mses,
    mean_pred = row_means,
    residual = Y_true - row_means,
    lower_ci = row_means - z_val * sqrt(row_vars),
    upper_ci = row_means + z_val * sqrt(row_vars),
    stage2_quantiles_str = df$stage2_quantiles_str[1],
    stage2_knots = df$stage2_knots,
    study_knots = df$study_knots,
    rank_method = df$rank_method,
    rank_id = df$rank_id
  )
}

all_metrics_no <- lapply(sim_data_no, function(df) {
  lapply(methods, function(m) {
    df_filtered <- df %>% filter(method == m)
    calculate_metrics(df_filtered, level = 0.95) %>%
      mutate(method = m)
  }) %>% bind_rows()
})
```
# Summary of all
```{r}
set_summary <- function(df_list, 
                        metrics = c("bias", "variance", "mse"), 
                        dp = 6){
  full_df <- data.frame()
  for (df in df_list) {
    group_vars <- c("method")
    df_summary <- df %>%
      group_by(across(all_of(group_vars))) %>%
      summarise(
        across(all_of(metrics),
               list(
                 mean = ~round(mean(.x, na.rm = TRUE), dp),
                 sd   = ~round(sd(.x, na.rm = TRUE), dp),
                 min  = ~round(min(.x, na.rm = TRUE), dp),
                 max  = ~round(max(.x, na.rm = TRUE), dp)
               ),
               .names = "{.fn}_{.col}"
        ),
        .groups = "drop"
      )
    full_df <- rbind(full_df, df_summary)
  }
  
  return(full_df)
}

# Apply summary to all_metrics_no
summary_all <- set_summary(all_metrics_no, metrics = c("mse", "variance", "bias"))
summary_all
```
# Bias, Variance, MSE plot
## n=1800
### line plot
```{r, fig.height=10, fig.width=7}
df_all <- bind_rows(all_metrics_no)

# Filter only top rank (rank_id == 1) and method matches rank_method
df_plot <- df_all %>%
  filter(rank_id %in% 1:top, method == rank_method) %>%
  mutate(line_id = paste0(method, "_", study_knots)) %>%  # new identifier
  pivot_longer(
    cols = c("bias", "variance", "mse"),
    names_to = "metric_name",
    values_to = "metric_value"
  )

# Split into three data frames
df_rank1 <- df_plot %>% filter(rank_id == 1)
df_rank2 <- df_plot %>% filter(rank_id == 2)
df_rank3 <- df_plot %>% filter(rank_id == 3)

quantiles_numeric <- knots_to_numeric(df_plot$stage2_quantiles_str[1])

# # Plot all lines in one figure
# ggplot(df_plot, aes(x = Age, y = metric_value, color = line_id)) +
#   geom_line(size = 1) +
#   geom_vline(
#     xintercept = quantiles_numeric, 
#     linetype = "dashed", color = "grey40") +
#   facet_wrap(~metric_name, scales = "free", ncol = 1) +
#   theme_minimal() +
#   labs(
#     x = "Age",
#     y = "Value",
#     color = "Ranked Method"
#   ) +
#   theme(
#     legend.position = "bottom",
#     panel.spacing = unit(1, "lines"),
#     strip.background = element_rect(fill = "white")
#   )
```
```{r}
# Base plot template
base_plot <- function(data) {
  ggplot(data, aes(x = Age, y = metric_value, color = line_id)) +
  geom_line(size = 1) +
  geom_vline(xintercept = quantiles_numeric, linetype = "dashed", color = "grey40") +
  facet_wrap(~metric_name, ncol = 1, scales = "free_y") +
  theme_minimal() +
  labs(x = "Age", y = "Value", color = "Method") +
  theme(legend.position = "bottom")
}

# Generate plots
p1 <- base_plot(df_rank1) + ggtitle("Rank ID: 1")
p2 <- base_plot(df_rank2) + ggtitle("Rank ID: 2")
p3 <- base_plot(df_rank3) + ggtitle("Rank ID: 3")

# List of plots
list(p1, p2, p3)
```

### CI True Value
```{r, fig.height=7, fig.width=5}
# ggplot(df_plot, aes(x = Age, y = mean_pred, color = method, fill = method, group)) +
#   geom_line(size = 1) +
#   geom_vline(
#     xintercept = quantiles_numeric, 
#     linetype = "dashed", color = "grey40") +
#   geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.2, color = NA) +
#   geom_line(aes(y = Y_true), color = "black", linetype = "dashed") +
#   # facet_wrap(~study_knots, ncol = 1) +
#   theme_minimal() +
#   labs(
#     x = "Age",
#     y = "Predicted Y",
#     color = "Method",
#     fill = "Method",
#     title = "Predicted Values with Confidence Intervals by Knots"
#   ) +
#   theme(
#     legend.position = "bottom",
#     panel.spacing = unit(1.5, "lines"),
#     strip.background = element_rect(fill = "white")
#   )
```
```{r}
# Base plot template
base_plot_CI <- function(data) {
  ggplot(data, aes(x = Age, y = mean_pred, color = method, fill = method, group)) +
    geom_line(size = 1) +
    geom_vline(
      xintercept = quantiles_numeric,
      linetype = "dashed", color = "grey40") +
    geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.2, color = NA) +
    geom_line(aes(y = Y_true), color = "black", linetype = "dashed") +
    # facet_wrap(~study_knots, ncol = 1) +
    theme_minimal() +
    labs(
      x = "Age",
      y = "Predicted Y",
      color = "Method",
      fill = "Method",
      title = "Predicted Values with Confidence Intervals by Knots"
    ) +
    theme(
      legend.position = "bottom",
      panel.spacing = unit(1.5, "lines"),
      strip.background = element_rect(fill = "white")
    )
}

# Generate plots
p1 <- base_plot_CI(df_rank1) + ggtitle("Rank ID: 1")
p2 <- base_plot_CI(df_rank2) + ggtitle("Rank ID: 2")
p3 <- base_plot_CI(df_rank3) + ggtitle("Rank ID: 3")

# List of plots
list(p1, p2, p3)
```

